apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-radix
  labels:
    name: parsec-radix
spec:
  template:
    spec:
      containers:
        - image: anakli/cca:splash2x_radix
          name: parsec-radix
          resources:
            requests:
              cpu: "1.5"
            limits:
              cpu: "2.0"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "taskset -c 2-3 ./run -S splash2x -a run -p radix -i native -n 2",
            ]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
