apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-blackscholes
  labels:
    name: parsec-blackscholes
spec:
  template:
    spec:
      containers:
        - image: anakli/cca:parsec_blackscholes
          name: parsec-blackscholes
          resources:
            requests:
              cpu: "1.5"
            limits:
              cpu: "2.0"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "taskset -c 2-3 ./run -a run -S parsec -p blackscholes -i native -n 2",
            ]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
